name: PHP Coding Standards

on:
  push:
    paths:
      - '**.php'

jobs:
  phpcs:
    name: PHP Coding Standards
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

    - name: Install PHPCS & WPCS
      run: composer require wp-coding-standards/wpcs

    # PHPCS doesn't locate the WordPress rules alone, we need to tell PHPCS where to find them.
    - name: Configure PHPCS
      run: vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs

    - name: Run PHPCS
      run: vendor/bin/phpcs ./
